import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "@/components/layouts";
import { CartProvider } from "@/contexts/cartContext";
import AuthProvider from "@/contexts/authContext/AuthProvider";
import { Toaster } from "react-hot-toast";
import { refreshTokenFetcher } from "@/lib/fetchData";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const res = await refreshTokenFetcher({
  //   url: "user/",
  //   method: "GET",
  //   credentials: "include",
  // });
  // console.log("res", res);
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col min-h-screen font-pcsmall overflow-x-hidden bg-[#f5f5f5]`}
      >
        <Toaster
          toastOptions={{
            style: {
              backgroundColor: "rgb(51 65 85)",
              color: "#fff",
            },
          }}
        />
        <AuthProvider>
          <CartProvider>
            <Header />
            <main className="flex-grow">{children}</main>
            <Footer />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
